<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B75F35K" ignored="0" name="Default test" tests="9" failures="1" timestamp="29 Oct 2018 09:51:48 GMT" time="4.468" errors="0">
  <testcase name="ValidateLogin" time="3.688" classname="smokeTest.ValidateSmokeTest">
    <failure type="java.lang.AssertionError" message="User is not being able to Login to the application expected [Shop - CCP] but found [CCP Login]">
      <![CDATA[java.lang.AssertionError: User is not being able to Login to the application expected [Shop - CCP] but found [CCP Login]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at smokeTest.ValidateSmokeTest.ValidateLogin(ValidateSmokeTest.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ValidateLogin -->
  <testcase name="ValidateMarkITPlacePage" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateMarkITPlacePage -->
  <testcase name="ValidateManageTab" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateManageTab -->
  <testcase name="ValidateInsightTab" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateInsightTab -->
  <testcase name="ValidateNotificationPage" time="0.001" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateNotificationPage -->
  <testcase name="ValidateLogo" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateLogo -->
  <testcase name="ValidateLogout" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateLogout -->
  <testcase name="ValidateForgetPswd" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateForgetPswd -->
  <testcase name="ValidateRegPage" time="0.0" classname="smokeTest.ValidateSmokeTest">
    <skipped/>
  </testcase> <!-- ValidateRegPage -->
</testsuite> <!-- Default test -->
